Epam.Avards/ViewModels/Award/EditAwardModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Epam.Awards.ViewModels.Award
{
    public class EditAwardModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Введите название")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Максимальная длина названия 50 символов")]
        [RegularExpression("([A-Za-z0-9_ -]+)", ErrorMessage = "только латинские символы, цифры, пробелы и дефисы")]
        public string Title { get; set; }
        [StringLength(250, MinimumLength = 1, ErrorMessage = "Максимальная длина описания 250 символов")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Изображение обязательно")]
        public HttpPostedFileBase image { get; set; }
    }
}

Epam.Avards/ViewModels/Award/InfoAwardModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Epam.Awards.ViewModels.Award
{
    public class InfoAwardModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Введите название")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Максимальная длина названия 50 символов")]
        [RegularExpression("([A-Za-z0-9 -]+)", ErrorMessage = "только латинские символы, цифры, пробелы и дефисы")]
        public string Title { get; set; }
        [StringLength(250, MinimumLength = 1, ErrorMessage = "Максимальная длина описания 250 символов")]
        public string Description { get; set; }
    }
}

Epam.Avards/ViewModels/Award/NewAvardModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Epam.Awards.ViewModels.Award
{
    public class NewAwardModel
    {
        [Required(ErrorMessage = "Введите название")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Максимальная длина названия 50 символов")]
        [RegularExpression("([A-Za-z0-9_ -]+)", ErrorMessage = "только латинские символы, цифры, пробелы и дефисы")]
        public string Title { get; set; }
        [StringLength(250, MinimumLength = 1, ErrorMessage = "Максимальная длина описания 250 символов")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Изображение обязательно")]
        public HttpPostedFileBase image { get; set; }
    }
}

Epam.Avards/Controllers/AwardsController.cs
using AutoMapper;
using Entities;
using Epam.Awards.Models;
using Epam.Awards.ViewModels.Award;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Epam.Avards.Controllers
{
    public class AwardsController : Controller
    {
        // GET: Award
        public ActionResult Index()
        {
            return View(Mapper.Map<IEnumerable<InfoAwardModel>>(ProviderLogic.AwardLogic.GetAll()));
        }
        [HttpGet]
        public ActionResult CreateAward()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateAward(NewAwardModel newAward)
        {
            if (ModelState.IsValid)
            {
                Award award = Mapper.Map<Award>(newAward);
                int newId = ProviderLogic.AwardLogic.Create(award);
                Image newImage = new Image();
                newImage.Type = newAward.image.ContentType;
                newImage.Name = newAward.image.FileName;
                newImage.Byte = new byte[newAward.image.ContentLength];
                newAward.image.InputStream.Read(newImage.Byte, 0, newAward.image.ContentLength);
                newImage.Id_Owner = newId;
                ProviderLogic.AwardLogic.AddImage(newImage);
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult InfoAward(int id)
        {
            return View(Mapper.Map<InfoAwardModel>(ProviderLogic.AwardLogic.GetByID(id)));
        }

        public ActionResult AddUserToAward(int id)
        {
            ViewBag.User = ProviderLogic.UserLogic.GetById(id);
            return View(Mapper.Map<IEnumerable<InfoAwardModel>>(ProviderLogic.AwardLogic.GetFreeAwards(id)));
        }
        public ActionResult SetUserToAward(int idAward, int idUser)
        {
            ProviderLogic.AwardLogic.SetAwardToUser(idUser, idAward);
            return RedirectToAction("InfoUser", "Users", new { id = idUser });
        }
        [HttpGet]
        public ActionResult EditAward(int id)
        {
            return View(Mapper.Map<InfoAwardModel>(ProviderLogic.AwardLogic.GetByID(id)));
        }
        [HttpPost]
        public ActionResult EditAward(InfoAwardModel updateAward, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                Award award = Mapper.Map<Award>(updateAward);
                if (image != null)
                {
                    Image newImage = new Image();
                    newImage.Type = image.ContentType;
                    newImage.Name = image.FileName;
                    newImage.Byte = new byte[image.ContentLength];
                    image.InputStream.Read(newImage.Byte, 0, image.ContentLength);
                    ProviderLogic.AwardLogic.UpdateImage(award.ID, newImage);
                }
                ProviderLogic.AwardLogic.Update(award);
                return RedirectToAction("InfoAward", "Awards", new { id = updateAward.ID });
            }
            return View(updateAward);
        }
        [HttpGet]
        public ActionResult DeleteAward(int id)
        {
            return View(Mapper.Map<InfoAwardModel>(ProviderLogic.AwardLogic.GetByID(id)));
        }
        [HttpPost]
        public ActionResult DeleteAward(Award award)
        {
            ProviderLogic.AwardLogic.Delete(award.ID);
            return RedirectToAction("Index");
        }
        public ActionResult CancelAwardToUser(int idUser, int idAward)
        {
            ProviderLogic.AwardLogic.CancelAwardToUser(idUser, idAward);
            return RedirectToAction("InfoUser", "Users", new { id = idUser });
        }

        public ActionResult GetByName(string name)
        {
            InfoAwardModel award = Mapper.Map<InfoAwardModel>(ProviderLogic.AwardLogic.GetByName(name));
            if (award != null)
            {
                ViewBag.Awards = ProviderLogic.AwardLogic.GetByIdUser(award.ID);
            }
            return View("InfoAward", award);
        }
        public ActionResult GetByLetterName(string searchAwardByLetterName)
        {
            IEnumerable<InfoAwardModel> awards = Mapper.Map<IEnumerable<InfoAwardModel>>(ProviderLogic.AwardLogic.GetByLetterName(searchAwardByLetterName));
            if (awards != null)
            {
                return View("Index", awards);
            }
            return RedirectToAction("Index");
        }

        public ActionResult GetByPartName(string searchAwardByPartName)
        {
            IEnumerable<InfoAwardModel> awards = Mapper.Map<IEnumerable<InfoAwardModel>>(ProviderLogic.AwardLogic.GetByPartName(searchAwardByPartName));
            if (awards != null)
            {
                return View("Index", awards);
            }
            return RedirectToAction("Index");
        }
        public ActionResult SearchByName(string name)
        {
            IEnumerable<InfoAwardModel> awards;
            InfoAwardModel award = Mapper.Map<InfoAwardModel>(ProviderLogic.AwardLogic.GetByName(name));
            if (award != null)
            {
                return View("InfoAward", award);
            }
            if (name.Count() == 1)
            {
                awards = Mapper.Map<IEnumerable<InfoAwardModel>>(ProviderLogic.AwardLogic.GetByLetterName(name));
                if (awards != null)
                {
                    return View("Index", awards);
                }
            }
            awards = Mapper.Map<IEnumerable<InfoAwardModel>>(ProviderLogic.AwardLogic.GetByPartName(name));
            if (awards != null)
            {
                return View("Index", awards);
            }
            return RedirectToAction("Index");

        }
    }
}

Epam.Avards/Controllers/ImageController.cs
using Entities;
using Epam.Awards.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Epam.Awards.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public FileContentResult GetImageByUser(int id, int newWidth, int maxHeight, bool reduceOnly)
        {
            Image image = ProviderLogic.UserLogic.GetImageByUser(id, newWidth, maxHeight, reduceOnly);
            if (image != null)
            {
                return File(image.Byte, image.Type);
            }
            return null;
        }

        public FileContentResult GetImageByAward(int id, int newWidth, int maxHeight, bool reduceOnly)
        {
            Image image = ProviderLogic.AwardLogic.GetImageByAward(id, newWidth, maxHeight, reduceOnly);
            if (image != null)
            {
                return File(image.Byte, image.Type);
            }
            return null;
        }
    }
}

Epam.Avards/Views/Awards/AddUserToAward.cshtml
@model  IEnumerable<Epam.Awards.ViewModels.Award.InfoAwardModel>
@{
    ViewBag.Title = "AddUserToAward";
}
@section style{
    <link href="~/Content/Style/StyleTable.css" rel="stylesheet" />
}
<h3>Награждение пользователя @ViewBag.User.Name</h3>
<div class="rTable">
    <div class="rTableRow">
        <div class="cellLeft">
            <h4>Изображение</h4>
        </div>
        <div class="cellMiddle">
            <h4>Название</h4>
        </div>
        <div class="cellMiddle">
            <h4>Описание</h4>
        </div>
        <div class="cellRight">
            <h4>Награждение</h4>
        </div>
    </div>
    @foreach (var award in Model)
    {
        <div class="rTableRow">
            <div class="cellLeft">
                <img class="img-rounded" src="@Url.Action("GetImageByAward", "Image", new { award.ID, newWidth = 100, maxHeight= 100, reduceOnly = true})" />
            </div>
            <div class="cellMiddle">
                @award.Title
            </div>
            <div class="cellMiddle">
                @award.Description
            </div>
            <div class="cellRight">
                <button data-href="@Url.Action("SetUserToAward", "Awards", new { idAward = award.ID, idUser =  ViewBag.User.ID})" class="buttonOnclik btn btn-success">Наградить</button>
            </div>
        </div>
    }
</div>

Epam.Avards/Views/Awards/CreateAward.cshtml
@model  Epam.Awards.ViewModels.Award.NewAwardModel
@{
    ViewBag.Title = "CreateAward";
}
<h3>Создание награды</h3>
@using (Html.BeginForm("CreateAward", "Awards", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3">Фото (не обязательно)</label>
            <div class="col-md-9">
                <a class='btn btn-primary' href='javascript:;'>
                    Выберите изображение...
                    <input type="file" multiple accept="image/*" name="Image" class="loadImage">
                </a>
                &nbsp;
                <span class='label label-info' id="upload-file-info"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Вернуться обратно", "Index")
</div>

Epam.Avards/Views/Awards/DeleteAward.cshtml
@model Epam.Awards.ViewModels.Award.InfoAwardModel
@{
    ViewBag.Title = "DeleteAward";
}
<h3>Вы действительно хотите удалить эту награду?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    @using (Html.BeginForm("DeleteAward", "Awards", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            @Html.ActionLink("Вернуться к списку наград", "Index")
        </div>
    }
</div>

Epam.Avards/Views/Awards/DeleteAwards.cshtml
@model Epam.Awards.ViewModels.Award.InfoAwardModel
@{
    ViewBag.Title = "DeleteAward";
}
<h3>Вы действительно хотите удалить эту награду?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    @using (Html.BeginForm("DeleteAward", "Awards", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-danger" /> |
            @Html.ActionLink("Вернуться к списку наград", "Index")
        </div>
    }
</div>

Epam.Avards/Views/Awards/EditAward.cshtml
@model  Epam.Awards.ViewModels.Award.InfoAwardModel
@{
    ViewBag.Title = "EditAward";
}
<h3>Редактирование награды</h3>
@using (Html.BeginForm("EditAward", "Awards", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3">
            </div>
            <img class="img-rounded" src="@Url.Action("GetImageByAward", "Image", new { Model.ID, newWidth = 200, maxHeight= 200, reduceOnly = true})" />
        </div>
        <div class="form-group">
            <label class="control-label col-md-3">Edit image</label>
            <div class="col-md-9">
                <a class='btn btn-primary' href='javascript:;'>
                    Выберите изображение...
                    <input type="file" multiple accept="image/*" name="Image" class="loadImage">
                </a>
                &nbsp;
                <span class='label label-info' id="upload-file-info"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить изменения" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Вернуться к списку наград", "Index")
</div>

Epam.Avards/Views/Awards/Index.cshtml
@model IEnumerable<Epam.Awards.ViewModels.Award.InfoAwardModel>
@{
    ViewBag.Title = "Awards";
}
@section style{
    <link href="~/Content/Style/StyleTable.css" rel="stylesheet" />
}
<h3 class="text-center">Награды</h3>
<button data-href="/create-award" class="buttonOnclik btn btn-success">Добавить награду</button>
<div class="rTable">
    <div class="rTableRow">
        <div class="cellLeft">
            <h4>Изображение</h4>
        </div>
        <div class="cellMiddle">
            <h4>Название</h4>
        </div>
        <div class="cellMiddle">
            <h4>Описание</h4>
        </div>
        <div class="cellRight">
            <h4>Действия</h4>
        </div>
    </div>
    @foreach (var award in Model)
    {
        <div class="rTableRow tableRowHover">
            <div class="cellLeft">
                <img class="img-rounded imageHover" src="@Url.Action("GetImageByAward", "Image", new { award.ID, newWidth = 150, maxHeight= 150, reduceOnly = true})" />
            </div>
            <div class="cellMiddle">
                @award.Title
            </div>
            <div class="cellMiddle">
                @award.Description
            </div>
            <div class="cellRight">
                <button data-href="/award/@award.ID" class="buttonOnclik btn btn-info">Информация</button>
                <button data-href="/award/@award.ID/edit" class="buttonOnclik btn btn-success">Редактировать</button>
                <button data-href="/award/@award.ID/delete" class="buttonOnclik btn btn-danger">Удалить</button>
            </div>
        </div>
    }
</div>
<br />
@using (Html.BeginForm("SearchByName", "Awards", FormMethod.Post))
{
    <div class="form-inline">
        <input id="name" name="name" placeholder="" class="form-control" />
        <input type="submit" value="Поиск по названию" class="btn btn-info btn-sm" />
    </div>
}

Epam.Avards/Views/Awards/InfoAward.cshtml
@model Epam.Awards.ViewModels.Award.InfoAwardModel
@{
    ViewBag.Title = "InfoAward";
}
<h3>Информация о награде</h3>
<div>
    @if (Model == null)
    {
        <span>Награды с таким названием не существует</span>
    }
    else
    {
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt>
                <h4>Image</h4>
            </dt>
            <dd>
                <img class="img-rounded imageHover" src="@Url.Action("GetImageByAward", "Image", new { Model.ID, newWidth = 200, maxHeight= 200, reduceOnly = true})" />
            </dd>
        </dl>
    }
</div>
<p>
    @Html.ActionLink("Посмотреть все существующие награды", "Index")
</p>